#!/usr/bin/env bash
# Build the GitHub Release body markdown for a Doove release tag.
#
# Inputs (env vars):
#   TAG       — release tag (e.g. v1.2.3)
#   PREV_TAG  — previous release tag for the compare link (may be empty)
#   REPO      — owner/repo slug (e.g. maboaimana4-source/doove-new)
#
# Outputs:
#   - Writes the assembled markdown to the file path in $1, or a mktemp file.
#   - When $GITHUB_OUTPUT is set (running in GitHub Actions), also writes:
#       found=true|false   — whether CHANGELOG.md had a section for this tag
#       body=<multiline>   — the full body as a heredoc output
#
# The structure mirrors what release-desktop.yml used to inline:
#   1. What's new (curated from CHANGELOG.md or auto-generated by GitHub)
#   2. Downloads — per-platform asset table
#   3. First launch on macOS — Gatekeeper / xattr workaround (prominent so
#      users hitting "is damaged" find the fix without scrolling)
#   4. System requirements
#   5. Verifying the download — attestation + Windows SmartScreen note
#   6. Full changelog compare link (when PREV_TAG is known)
#   7. Footer (issues link)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

: "${TAG:?TAG is required}"
: "${REPO:?REPO is required}"
PREV_TAG="${PREV_TAG:-}"

body_file="${1:-$(mktemp)}"
version="${TAG#v}"

# 1. What's new — curated CHANGELOG section, or fall back to GH auto-notes.
found="false"
if node scripts/extract-changelog.mjs "$version" --out changelog-section.md > /dev/null 2>&1; then
  found="true"
  {
    echo "## What's new in ${TAG}"
    echo
    cat changelog-section.md
    echo
  } > "$body_file"
else
  echo "::warning::No CHANGELOG.md section for ${version}; falling back to auto-generated notes."
  : > "$body_file"
fi

# 2. Downloads — point users at the right asset for their platform.
{
  echo "## Downloads"
  echo
  echo "| Platform | Asset |"
  echo "| --- | --- |"
  echo "| Windows 10/11 (x64) — installer | \`doove_${version}_x64-setup.exe\` or \`doove_${version}_x64_en-US.msi\` |"
  echo "| Windows 10/11 (x64) — Store package | \`doove_${version}_x64.msix\` |"
  echo "| macOS (Apple Silicon) — beta | \`doove_${version}_aarch64.dmg\` · or \`brew install --cask maboaimana4-source/doove-new/doove\` |"
  echo "| macOS (Intel) — beta | \`doove_${version}_x64.dmg\` · or \`brew install --cask maboaimana4-source/doove-new/doove\` |"
  echo "| Linux (x64) — universal | \`doove_${version}_amd64.AppImage\` |"
  echo "| Linux (x64) — Debian/Ubuntu | \`doove_${version}_amd64.deb\` |"
  echo
  echo "All assets ship with [GitHub artifact attestations](https://docs.github.com/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds) for build provenance."
  echo
} >> "$body_file"

# 2b. Homebrew (macOS) — the recommended macOS path. The cask auto-strips the
# quarantine attribute, so brew users skip the Gatekeeper workaround below.
{
  echo "## Install with Homebrew (macOS)"
  echo
  echo "macOS support is in **beta**. The smoothest way on is Homebrew — it picks the right build for your chip and **removes the Gatekeeper quarantine for you**, so you never hit the \"is damaged\" error:"
  echo
  echo '```sh'
  echo "brew install --cask maboaimana4-source/doove-new/doove"
  echo '```'
  echo
  echo "Prefer the short name? Tap once, then install (and upgrade) with:"
  echo
  echo '```sh'
  echo "brew tap maboaimana4-source/doove-new"
  echo "brew install --cask doove"
  echo '```'
  echo
} >> "$body_file"

# 3. macOS first-launch — section placed prominently so users who hit the
# "is damaged" error find the one-liner fix without scrolling. The literal
# error string is included so search engines surface this release page
# when users paste it into Google. Builds are not yet Apple-notarized;
# until that changes, the quarantine attribute on a downloaded DMG
# triggers Gatekeeper to refuse the app with that exact wording.
{
  echo "## First launch on macOS"
  echo
  echo "> Installed with **Homebrew**? Skip this section — the cask removes the quarantine attribute for you."
  echo
  echo "If you see"
  echo
  echo "> \"Doove\" is damaged and can't be opened. You should move it to the Trash."
  echo
  echo "**the download is fine** — macOS is just blocking the app because we haven't signed and notarized this build with Apple yet. Strip the quarantine attribute once, then open normally:"
  echo
  echo '```sh'
  echo "xattr -dr com.apple.quarantine /Applications/Doove.app"
  echo '```'
  echo
  echo "After that, first launch will prompt for **Screen Recording**, **Microphone**, and **Camera** permission in System Settings → Privacy & Security. Grant the ones you intend to record from and restart the app."
  echo
  echo "Once we ship a notarized build (tracked under [Phase 7 of the cross-platform plan](https://github.com/${REPO}/blob/main/apps/desktop/docs/cross-platform-support-plan.md#phase-7--packaging-signing--distribution-release-path-already-wired)) this step will go away."
  echo
} >> "$body_file"

# 4. System requirements.
{
  echo "## System requirements"
  echo
  echo "- **Windows**: Windows 10 1809+ or Windows 11, x64. WebView2 Runtime (bundled by the installer)."
  echo "- **macOS**: macOS 11 Big Sur or later. Universal screen recording, microphone, and accessibility permissions are required at first launch."
  echo "- **Linux**: glibc 2.35+ (Ubuntu 22.04 / Fedora 36 / Debian 12 or newer). PipeWire 0.3+ recommended for system audio capture."
  echo
} >> "$body_file"

# 5. Verifying the download (provenance + Windows SmartScreen).
{
  echo "## Verifying the download"
  echo
  echo "Every asset ships with a [GitHub artifact attestation](https://docs.github.com/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds) so you can confirm the build came from this repository's CI:"
  echo
  echo '```sh'
  echo "gh attestation verify path/to/downloaded-asset -R ${REPO}"
  echo '```'
  echo
  echo "**Windows** — if SmartScreen blocks the installer, click *More info → Run anyway* after verifying the attestation above."
  echo
} >> "$body_file"

# 6. Full changelog — compare link.
if [[ -n "${PREV_TAG}" ]]; then
  {
    echo "## Full changelog"
    echo
    echo "**Compare:** https://github.com/${REPO}/compare/${PREV_TAG}...${TAG}"
    echo
  } >> "$body_file"
fi

# 7. Issues / feedback footer.
{
  echo "---"
  echo
  echo "Found a bug or have a feature request? [Open an issue](https://github.com/${REPO}/issues/new/choose)."
} >> "$body_file"

# Surface state to GitHub Actions when running in CI.
if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  echo "found=${found}" >> "$GITHUB_OUTPUT"
  {
    echo "body<<__BODY_EOF__"
    cat "$body_file"
    echo "__BODY_EOF__"
  } >> "$GITHUB_OUTPUT"
fi

# Also echo the body path so local runs can inspect it.
echo "Release body written to: $body_file"
