<script lang="ts">
	import { browser } from "$app/environment";
	import { page } from "$app/state";
	import { SeoMeta } from "$lib/components";
	import Logo from "$lib/logo.svelte";
	import {
	  ArrowRight,
	  AtSign,
	  Check,
	  ChevronDown,
	  Clock,
	  Code,
	  Copy,
	  Download,
	  ExternalLink,
	  Eye,
	  Globe,
	  LayoutDashboard,
	  Link2,
	  Lock,
	  LogOut,
	  Mail,
	  Megaphone,
	  MessageSquare,
	  Moon,
	  RotateCcw,
	  Settings,
	  Share2,
	  ShieldOff,
	  Sun,
	  Trash2,
	  User,
	  UserCheck,
	  Users,
	  Film,
	} from "@lucide/svelte";
	import { goto, invalidateAll } from "$app/navigation";
	import { analytics } from "$lib/analytics/client";
	import { authClient } from "$lib/auth/client";
	import { mode as themeMode, toggleMode } from "@doove/ui/theme";
	import { DoovePlayer, type DoovePlayerApi } from "@doove/player";
	import { Button } from "@doove/ui/button";
	import * as Dialog from "@doove/ui/dialog";
	import * as DropdownMenu from "@doove/ui/dropdown-menu";
	import { Input } from "@doove/ui/input";
	import { Label } from "@doove/ui/label";
	import { toast } from "@doove/ui/sonner";
	import * as Tooltip from "@doove/ui/tooltip";
	import { cn } from "@doove/ui/utils";
	import { onMount, untrack } from "svelte";
	import { cubicOut, quintOut } from "svelte/easing";
	import { Tween } from "svelte/motion";
	import { fade, fly, scale, slide } from "svelte/transition";
	import {
		REACTION_EMOJI,
		deleteComment,
		loadEngagement,
		postComment,
		rememberViewerName,
		shareSessionId,
		storedViewerName,
		toggleReaction,
		type ReactionCount,
		type ShareComment,
	} from "$lib/share/client";

	let { data } = $props();

	// `access` is the server-resolved permission envelope. When `ok` is
	// true it carries the doove + share + canManage; when false it
	// carries the reason + (for same-team viewers) the owner contact so
	// the denial card can render a "request access" affordance.
	const access = $derived(data.access);
	const okAccess = $derived(access.ok ? access : null);
	const deniedAccess = $derived(access.ok ? null : access);
	const doove = $derived(okAccess?.doove);

	// ── Account-less invitee claim (selected shares) ──────────────────────
	// A denied viewer of a `selected` share can request an email access link.
	let claimEmail = $state("");
	let claimState = $state<"idle" | "sending" | "sent">("idle");
	// The verify endpoint bounces back with ?claim=invalid on a bad/expired link.
	const claimInvalid = $derived(page.url.searchParams.get("claim") === "invalid");

	async function submitClaim(e: SubmitEvent) {
		e.preventDefault();
		const email = claimEmail.trim();
		if (!email || claimState === "sending") return;
		claimState = "sending";
		try {
			const res = await fetch(`/api/share/${page.params.id}/claim`, {
				method: "POST",
				headers: { "content-type": "application/json" },
				body: JSON.stringify({ email }),
			});
			if (!res.ok) throw new Error((await res.text()) || "Couldn't send the link.");
			claimState = "sent";
		} catch (err) {
			claimState = "idle";
			toast.error((err as Error)?.message ?? "Couldn't send the link.");
		}
	}
	const shareMeta = $derived(okAccess?.share);
	const canManage = $derived(okAccess?.canManage ?? false);
	// Exact source aspect ratio, when the doove row carries its dimensions.
	// Passing this to the player reserves the precise box before metadata loads
	// → zero layout shift. Null on legacy rows, where the player falls back to
	// its 16/9 placeholder and adjusts once the real dimensions decode.
	const playerAspect = $derived(
		doove?.width && doove?.height ? `${doove.width} / ${doove.height}` : null,
	);
	const slug = $derived(shareMeta?.slug ?? doove?.id ?? "");
	const isDemo = $derived(slug === "demo");

	// ── Social preview (dynamic OG) ───────────────────────────────────
	// Shared dooves unfurl with a branded card that surfaces the doove's
	// own title + description and who shared it, generated by /api/og so the
	// Doove wordmark/footer branding stays consistent with the marketing
	// pages. Denied/private shares fall back to a generic branded card. The
	// page stays `noindex` either way (see <svelte:head> below) — rich link
	// previews without making private content crawlable.
	const ogTitle = $derived(doove?.title ?? "Private doove");
	const ogDescription = $derived(
		doove?.description?.trim() ||
			(doove
				? "Recorded, polished, and shared with Doove."
				: "This doove is private."),
	);
	const ogEyebrow = $derived(doove ? `Shared by ${doove.sharedBy}` : undefined);

	// Record a real share view, keyed to the anonymous shareView session id so
	// PostHog reconciles with the first-party watch-metrics table. Viewers are
	// never identified — this stays anonymous regardless of consent.
	onMount(() => {
		if (!browser || !okAccess || isDemo) return;
		analytics.capture("share_viewed", {
			visibility: shareMeta?.visibility,
			share_session_id: shareSessionId(),
		});
	});

	// `requiresPassword` is set by the page loader when the share has a
	// passwordHash and the viewer doesn't carry a valid unlock cookie. In
	// that case `doove.src` is empty and we render the prompt below
	// instead of the player. On a successful unlock we `invalidateAll()`
	// so the loader re-runs, signs the URL, and the player mounts.
	const requiresPassword = $derived(
		Boolean(okAccess && "requiresPassword" in access && access.requiresPassword),
	);
	let passwordInput = $state("");
	let unlocking = $state(false);
	let unlockError = $state<string | null>(null);
	async function submitUnlock(e: SubmitEvent) {
		e.preventDefault();
		if (!shareMeta || unlocking || !passwordInput) return;
		unlocking = true;
		unlockError = null;
		try {
			const res = await fetch(`/api/share/${shareMeta.slug}/unlock`, {
				method: "POST",
				headers: { "content-type": "application/json" },
				body: JSON.stringify({ password: passwordInput }),
			});
			if (!res.ok) {
				unlockError =
					res.status === 401 ? "Wrong password. Try again." : "Couldn't unlock.";
				return;
			}
			passwordInput = "";
			await invalidateAll();
		} catch {
			unlockError = "Network error. Try again.";
		} finally {
			unlocking = false;
		}
	}

	// The toggle below writes the standard {public, team, private} scopes
	// (`workspace` shows as "team", its alias). The richer `selected`
	// specific-people allowlist is created from the share dialog, not here —
	// but we surface it ACCURATELY (instead of masking it as "Only me") so the
	// owner sees the real scope and can switch off it.
	type LegacyVisibility = "public" | "team" | "private";
	const toLegacyVisibility = (v: string): LegacyVisibility => {
		if (v === "public") return "public";
		if (v === "team" || v === "workspace") return "team";
		return "private";
	};
	// The share's true current scope (full enum), synced from the server and
	// updated optimistically on toggle.
	let currentScope = $state<string>(
		untrack(() => (data.access.ok ? data.access.share.visibility : "public")),
	);
	$effect(() => {
		if (access.ok) currentScope = access.share.visibility;
	});
	const isSelectedScope = $derived(currentScope === "selected");
	// Which toggle row reads as active — none while on the specific-people
	// allowlist, so "selected" no longer masquerades as "Only me".
	const activeScope: LegacyVisibility | null = $derived(
		isSelectedScope ? null : toLegacyVisibility(currentScope),
	);
	let updatingVisibility = $state(false);

	async function updateVisibility(next: "public" | "team" | "private") {
		if (!shareMeta || !canManage || updatingVisibility) return;
		if (next === activeScope) return;
		const previous = currentScope;
		currentScope = next;
		updatingVisibility = true;
		try {
			await toast.promise(
				(async () => {
					const res = await fetch(`/api/share/${shareMeta.slug}/access`, {
						method: "PATCH",
						headers: { "content-type": "application/json" },
						body: JSON.stringify({ visibility: next }),
					});
					if (!res.ok) {
						const message = await res.text().catch(() => "Couldn't update access");
						throw new Error(message || "Couldn't update access");
					}
				})(),
				{
					loading: "Updating who can view…",
					success:
						next === "public"
							? "Anyone with the link can view."
							: next === "team"
								? "Restricted to your team."
								: "Only you can view.",
					error: (err) => (err as Error)?.message ?? "Couldn't update access.",
				},
			);
		} catch {
			currentScope = previous;
		} finally {
			updatingVisibility = false;
		}
	}

	// ── Player wiring ────────────────────────────────────────────────
	function parseTimeParam(raw: string | null): number {
		if (!raw) return 0;
		const t = raw.trim().toLowerCase();
		if (/^\d+$/.test(t)) return Number(t);
		let total = 0;
		const h = t.match(/(\d+)h/);
		const m = t.match(/(\d+)m/);
		const s = t.match(/(\d+)s/);
		if (h) total += Number(h[1]) * 3600;
		if (m) total += Number(m[1]) * 60;
		if (s) total += Number(s[1]);
		return total;
	}

	const initialSeekSeconds = untrack(() => parseTimeParam(page.url.searchParams.get("t")));

	let api = $state<DoovePlayerApi | null>(null);

	// Re-seek every time the player API publishes — covers the initial
	// `?t=` URL seed and any later remount. Reading `currentTime` via
	// `untrack` so this effect only re-runs when `api` itself changes.
	$effect(() => {
		if (!api) return;
		const target = untrack(() => Math.max(initialSeekSeconds, currentTime));
		if (target > 0) api.seek(target);
	});

	let currentTime = $state(initialSeekSeconds);
	const smoothedTime = new Tween(0, { duration: 120, easing: cubicOut });
	let watchedPct = $state(0);
	let isPlaying = $state(false);
	// True once the video reaches the end — drives the CTA end-card overlay.
	let ended = $state(false);

	$effect(() => {
		smoothedTime.set(currentTime);
	});

	// First-party view recording. Bumps the cached view count AND — critically
	// — refreshes `doove.lastViewedAt`, which the Free-tier expiry sweep keys
	// off (without this, watched dooves still archive at 14 days). Anonymous:
	// keyed only by the share session fingerprint. Skipped for the demo (no
	// real share row) and SSR. `keepalive` lets the "ended" beacon survive a
	// tab close.
	let viewStartSent = false;
	function recordView(event: "start" | "ended") {
		if (!browser || isDemo || !slug) return;
		if (event === "start") {
			if (viewStartSent) return;
			viewStartSent = true;
		}
		try {
			void fetch(`/api/share/${slug}/view`, {
				method: "POST",
				headers: { "content-type": "application/json" },
				body: JSON.stringify({
					sessionId: shareSessionId(),
					event,
					watchPct: Math.round(watchedPct),
					// Acquisition source — only meaningful on the first ("start")
					// beacon; the server reduces it to a bare host and drops self-refs.
					referrer: event === "start" ? document.referrer || null : null,
				}),
				keepalive: true,
			}).catch(() => {});
		} catch {
			// Never let a metrics beacon disrupt playback.
		}
	}

	function onEngagement(e: {
		type: "view-start" | "progress" | "ended";
		percent?: number;
		currentTime?: number;
	}) {
		if (e.type === "view-start") {
			isPlaying = true;
			ended = false;
			recordView("start");
		}
		if (e.type === "progress") {
			currentTime = e.currentTime ?? currentTime;
			watchedPct = e.percent ?? watchedPct;
			isPlaying = true;
			ended = false;
			// Some players jump straight to progress without a view-start; the
			// guard makes this idempotent so we still record the view once.
			recordView("start");
		}
		if (e.type === "ended") {
			watchedPct = 100;
			isPlaying = false;
			ended = true;
			recordView("ended");
		}
	}

	function replay() {
		ended = false;
		api?.seek(0);
		api?.play();
	}

	// ── Call-to-action (owner-defined "next step") ───────────────────
	let ctaLabel = $state(untrack(() => (data.access.ok ? data.access.share.ctaLabel : null)));
	let ctaUrl = $state(untrack(() => (data.access.ok ? data.access.share.ctaUrl : null)));
	const cta = $derived(ctaLabel && ctaUrl ? { label: ctaLabel, url: ctaUrl } : null);
	const showEndCard = $derived(ended && cta != null);

	// ── Comments + reactions (engagement layer) ──────────────────────
	let commentsEnabled = $state(
		untrack(() => (data.access.ok ? data.access.share.commentsEnabled : true)),
	);
	const watermark = $derived(shareMeta?.watermark ?? true);
	const viewsCount = $derived(shareMeta?.viewsCount ?? 0);

	let comments = $state<ShareComment[]>([]);
	let reactions = $state<ReactionCount[]>([]);
	let myReactions = $state<Set<string>>(new Set());
	let engagementLoaded = $state(false);
	let commentsOpen = $state(true);

	// Scroll-aware top bar: once the title scrolls under the sticky header
	// we fade the owner + title into the bar so the viewer keeps context
	// while reading/commenting. Driven off the title element itself via an
	// IntersectionObserver (the `-72px` top margin ≈ the header height).
	let titleAnchorEl = $state<HTMLElement | null>(null);
	let showBarTitle = $state(false);
	$effect(() => {
		const el = titleAnchorEl;
		if (!browser || !el) return;
		const io = new IntersectionObserver(
			([entry]) => {
				showBarTitle = !entry.isIntersecting;
			},
			{ rootMargin: "-72px 0px 0px 0px", threshold: 0 },
		);
		io.observe(el);
		return () => io.disconnect();
	});

	let sessionId = $state("");
	let viewerName = $state("");
	let draftText = $state("");
	let inputEl = $state<HTMLInputElement | null>(null);

	// Demo content so /share/demo stays a live design surface without a row
	// in the database (the engagement endpoints 404 for it).
	const DEMO_COMMENTS: ShareComment[] = [
		{ id: "d1", authorName: "Mia", atSeconds: 14, body: "Love the opening shot at [0:14] — crisp even after compression.", createdAt: 0, mine: false },
		{ id: "d2", authorName: "Dev", atSeconds: 52, body: "@Mia can we lift the audio bed ~3dB at [0:52]? Voice is competing.", createdAt: 0, mine: false },
		{ id: "d3", authorName: "Sara", atSeconds: 128, body: "This cut at 2:08 is sharp — worth showing the founder the full sequence.", createdAt: 0, mine: false },
	];
	const DEMO_REACTIONS: ReactionCount[] = [
		{ emoji: "👍", count: 12 },
		{ emoji: "❤️", count: 7 },
		{ emoji: "🔥", count: 4 },
		{ emoji: "🎉", count: 2 },
	];

	onMount(() => {
		sessionId = shareSessionId();
		viewerName = storedViewerName();
	});

	// Load engagement once the player surface is live (covers both the
	// initial mount and the post-unlock case, where the loader re-runs but
	// the component doesn't re-mount).
	$effect(() => {
		if (!browser || requiresPassword) return;
		const s = slug;
		if (!s || untrack(() => engagementLoaded)) return;
		loadAll(s);
	});

	async function loadAll(s: string) {
		engagementLoaded = true; // guard against the effect re-firing mid-await
		const sid = shareSessionId();
		sessionId = sid;
		if (s === "demo") {
			comments = DEMO_COMMENTS;
			reactions = DEMO_REACTIONS;
			myReactions = new Set();
			return;
		}
		try {
			const e = await loadEngagement(s, sid);
			comments = e.comments;
			reactions = e.reactions;
			myReactions = new Set(e.myReactions);
			commentsEnabled = e.commentsEnabled;
		} catch {
			// Leave the surface empty rather than blanking the page.
		}
	}

	async function refresh() {
		if (isDemo) return;
		try {
			const e = await loadEngagement(slug, sessionId);
			comments = e.comments;
			reactions = e.reactions;
			myReactions = new Set(e.myReactions);
			commentsEnabled = e.commentsEnabled;
		} catch {
			// best-effort
		}
	}

	function countFor(emoji: string): number {
		return reactions.find((r) => r.emoji === emoji)?.count ?? 0;
	}
	const totalReactions = $derived(reactions.reduce((sum, r) => sum + r.count, 0));

	async function react(emoji: string) {
		const had = myReactions.has(emoji);
		const nextSet = new Set(myReactions);
		const next = reactions.map((r) => ({ ...r }));
		const idx = next.findIndex((r) => r.emoji === emoji);
		if (had) {
			nextSet.delete(emoji);
			if (idx >= 0) {
				next[idx].count -= 1;
				if (next[idx].count <= 0) next.splice(idx, 1);
			}
		} else {
			nextSet.add(emoji);
			if (idx >= 0) next[idx].count += 1;
			else next.push({ emoji, count: 1 });
		}
		myReactions = nextSet;
		reactions = next;
		if (isDemo) return;
		try {
			await toggleReaction(slug, { sessionId, emoji, atSeconds: Math.floor(currentTime) });
		} catch {
			refresh();
		}
	}

	async function submitComment() {
		const text = draftText.trim();
		const name = viewerName.trim();
		if (!text || !name) return;
		rememberViewerName(name);
		const at = Math.floor(currentTime);
		if (isDemo) {
			comments = [
				...comments,
				{ id: `local-${comments.length}`, authorName: name, atSeconds: at, body: text, createdAt: 0, mine: true },
			];
			draftText = "";
			toast.success(`Posted at ${formatTime(at)}.`);
			return;
		}
		try {
			const c = await postComment(slug, { sessionId, authorName: name, atSeconds: at, body: text });
			comments = [...comments, c];
			draftText = "";
			toast.success(`Posted at ${formatTime(at)}.`);
		} catch (e) {
			toast.error((e as Error)?.message ?? "Couldn't post comment.");
		}
	}

	async function removeComment(id: string) {
		const prev = comments;
		comments = comments.filter((c) => c.id !== id);
		if (isDemo) return;
		try {
			await deleteComment(slug, id, sessionId);
		} catch (e) {
			comments = prev;
			toast.error((e as Error)?.message ?? "Couldn't delete comment.");
		}
	}

	function insertCurrentTimestamp() {
		const stamp = `[${formatTime(currentTime)}] `;
		const el = inputEl;
		if (!el) {
			draftText += stamp;
			return;
		}
		const start = el.selectionStart ?? draftText.length;
		const end = el.selectionEnd ?? draftText.length;
		draftText = draftText.slice(0, start) + stamp + draftText.slice(end);
		queueMicrotask(() => {
			el.focus();
			const pos = start + stamp.length;
			el.setSelectionRange(pos, pos);
		});
	}

	// ── Owner share settings (CTA + comments toggle) ─────────────────
	async function patchSettings(body: Record<string, unknown>) {
		const res = await fetch(`/api/share/${slug}/settings`, {
			method: "PATCH",
			headers: { "content-type": "application/json" },
			body: JSON.stringify(body),
		});
		if (!res.ok) {
			const message = await res.text().catch(() => "");
			throw new Error(message || "Couldn't update share settings");
		}
		return (await res.json()) as {
			ctaLabel?: string | null;
			ctaUrl?: string | null;
			commentsEnabled?: boolean;
		};
	}

	async function toggleCommentsEnabled() {
		const next = !commentsEnabled;
		commentsEnabled = next;
		if (isDemo) return;
		try {
			await patchSettings({ commentsEnabled: next });
			toast.success(next ? "Comments are on." : "Comments are off.");
		} catch (e) {
			commentsEnabled = !next;
			toast.error((e as Error)?.message ?? "Couldn't update comments.");
		}
	}

	let ctaDialogOpen = $state(false);
	let ctaLabelDraft = $state("");
	let ctaUrlDraft = $state("");
	let savingCta = $state(false);

	function openCtaEditor() {
		ctaLabelDraft = ctaLabel ?? "";
		ctaUrlDraft = ctaUrl ?? "";
		ctaDialogOpen = true;
	}

	async function saveCta(e: SubmitEvent) {
		e.preventDefault();
		const label = ctaLabelDraft.trim();
		const url = ctaUrlDraft.trim();
		if (label && !url) {
			toast.error("Add a link for the button.");
			return;
		}
		savingCta = true;
		if (isDemo) {
			ctaLabel = label || null;
			ctaUrl = url || null;
			ctaDialogOpen = false;
			savingCta = false;
			return;
		}
		try {
			const r = await patchSettings({ ctaLabel: label, ctaUrl: url });
			ctaLabel = r.ctaLabel ?? null;
			ctaUrl = r.ctaUrl ?? null;
			ctaDialogOpen = false;
			toast.success(ctaLabel ? "Call-to-action saved." : "Call-to-action removed.");
		} catch (err) {
			toast.error((err as Error)?.message ?? "Couldn't save the call-to-action.");
		} finally {
			savingCta = false;
		}
	}

	// ── Comment rich text (timestamps + mentions) ────────────────────
	type CommentSegment =
		| { kind: "text"; text: string }
		| { kind: "timestamp"; seconds: number; raw: string }
		| { kind: "mention"; name: string };

	function parseTimeToken(s: string): number {
		const parts = s.split(":").map((p) => Number(p));
		if (parts.some(Number.isNaN)) return 0;
		if (parts.length === 2) return parts[0]! * 60 + parts[1]!;
		if (parts.length === 3) return parts[0]! * 3600 + parts[1]! * 60 + parts[2]!;
		return 0;
	}

	function parseCommentText(text: string): CommentSegment[] {
		const re =
			/\[(\d{1,2}(?::\d{2}){1,2})\]|\b(\d{1,2}:\d{2}(?::\d{2})?)\b|@([A-Za-z][\w]{0,31})/g;
		const out: CommentSegment[] = [];
		let lastIdx = 0;
		let m: RegExpExecArray | null;
		while ((m = re.exec(text)) !== null) {
			if (m.index > lastIdx) out.push({ kind: "text", text: text.slice(lastIdx, m.index) });
			if (m[1] !== undefined) out.push({ kind: "timestamp", seconds: parseTimeToken(m[1]), raw: m[1] });
			else if (m[2] !== undefined) out.push({ kind: "timestamp", seconds: parseTimeToken(m[2]), raw: m[2] });
			else if (m[3] !== undefined) out.push({ kind: "mention", name: m[3] });
			lastIdx = m.index + m[0].length;
		}
		if (lastIdx < text.length) out.push({ kind: "text", text: text.slice(lastIdx) });
		return out;
	}

	function jumpTo(seconds: number) {
		api?.seek(seconds);
		if (!isPlaying) api?.play();
		ended = false;
		if (!browser) return;
		const url = new URL(window.location.href);
		const t = compactTime(seconds);
		if (t) url.searchParams.set("t", t);
		else url.searchParams.delete("t");
		window.history.replaceState({}, "", url.toString());
	}

	function formatTime(sec: number): string {
		const m = Math.floor(sec / 60);
		const s = Math.floor(sec % 60);
		return `${m}:${String(s).padStart(2, "0")}`;
	}

	function compactTime(sec: number): string {
		const s = Math.max(0, Math.floor(sec));
		if (s === 0) return "";
		const h = Math.floor(s / 3600);
		const m = Math.floor((s % 3600) / 60);
		const r = s % 60;
		let out = "";
		if (h) out += `${h}h`;
		if (m) out += `${m}m`;
		if (r || !out) out += `${r}s`;
		return out;
	}

	async function writeClipboard(text: string, okMsg: string) {
		try {
			await navigator.clipboard.writeText(text);
			toast.success(okMsg);
		} catch {
			toast.error("Couldn't copy to clipboard.");
		}
	}

	async function copyShareLink() {
		if (!browser) return;
		const url = new URL(window.location.href);
		url.searchParams.delete("t");
		await writeClipboard(url.toString(), "Share link copied.");
	}

	async function copyLinkAtCurrentTime() {
		if (!browser) return;
		const url = new URL(window.location.href);
		const t = compactTime(currentTime);
		if (t) url.searchParams.set("t", t);
		else url.searchParams.delete("t");
		await writeClipboard(
			url.toString(),
			t ? `Link copied at ${formatTime(currentTime)}.` : "Link copied.",
		);
	}

	async function copyEmbedCode() {
		if (!browser) return;
		const url = new URL(window.location.href);
		const iframe = `<iframe src="${url.toString()}" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`;
		await writeClipboard(iframe, "Embed code copied.");
	}

	// ── Viewer identity ──────────────────────────────────────────────
	type SessionShape = {
		data: { user?: { name?: string | null; email?: string | null; image?: string | null } | null } | null;
	};
	const session = authClient.useSession();
	const viewer = $derived(($session as unknown as SessionShape).data?.user ?? null);

	function initials(name: string | null | undefined, email: string | null | undefined): string {
		const src = (name ?? email ?? "?").trim();
		if (!src) return "?";
		const parts = src.split(/\s+/).filter(Boolean);
		if (parts.length >= 2) return (parts[0]![0]! + parts[1]![0]!).toUpperCase();
		return src.slice(0, 2).toUpperCase();
	}

	function commentHue(seed: string): number {
		let h = 0;
		for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
		return h % 360;
	}

	async function signOut() {
		await authClient.signOut();
		await goto("/");
	}
</script>

<SeoMeta title={ogTitle} description={ogDescription} eyebrow={ogEyebrow} />

<svelte:head>
	<!-- Rich previews are fine, but a shared link shouldn't be crawlable. -->
	<meta name="robots" content="noindex" />
</svelte:head>

{#if deniedAccess}
	<!-- Denial fallback. Same-team viewers get a "request access" CTA that
	     opens their mail client to the owner; strangers get a plain card.
	     Signed-out viewers see a sign-in nudge. -->
	<div class="relative grid min-h-screen place-items-center px-6 py-16 text-foreground">
		<div
			aria-hidden="true"
			class="pointer-events-none absolute inset-0 -z-10"
			style="background: radial-gradient(ellipse 60% 40% at 50% 0%, color-mix(in srgb, var(--color-primary) 6%, transparent), transparent 70%);"
		></div>
		<div
			aria-hidden="true"
			class="bg-grid bg-grid-fade pointer-events-none absolute inset-0 -z-10 opacity-25"
		></div>

		<div
			class="glass-card w-full max-w-md rounded-2xl border border-border-low/40 p-7 shadow-craft-xl"
			in:scale={{ start: 0.96, duration: 320, easing: quintOut, opacity: 0.6 }}
		>
			<div class="flex items-start gap-3">
				<span class="grid size-10 shrink-0 place-items-center rounded-xl bg-foreground/5 text-muted-foreground ring-1 ring-border/40">
					<ShieldOff class="size-5" />
				</span>
				<div class="min-w-0">
					<h1 class="text-lg font-semibold tracking-tight">You don't have access</h1>
					<p class="mt-1 text-sm text-muted-foreground">
						{#if deniedAccess.visibility === "selected"}
							This recording is shared with specific people. Enter your email to get a one-time access link — no account needed.
						{:else if deniedAccess.visibility === "team"}
							This doove is shared with a specific team. Ask the owner to add you, or sign in with an account that's a member.
						{:else if deniedAccess.visibility === "private"}
							This doove is private. Only the owner can view it.
						{:else}
							This share link isn't available to your account.
						{/if}
					</p>
				</div>
			</div>

			{#if deniedAccess.visibility === "selected"}
				<!-- Invite-only: email-based access claim. -->
				{#if claimState === "sent"}
					<div class="mt-5 rounded-xl border border-primary/30 bg-primary/8 p-4 text-sm" in:fly={{ y: 8, duration: 240, easing: cubicOut }}>
						<p class="flex items-center gap-2 font-medium text-foreground">
							<Check class="size-4 text-primary" />
							Check your inbox
						</p>
						<p class="mt-1 text-muted-foreground">
							If <span class="font-medium text-foreground">{claimEmail}</span> is on the access list, we've sent a link to open this recording.
						</p>
					</div>
				{:else}
					<form class="mt-5 flex flex-col gap-2" onsubmit={submitClaim}>
						{#if claimInvalid}
							<p class="text-xs text-destructive" in:slide={{ duration: 160 }}>
								That access link is invalid or has expired. Enter your email to get a fresh one.
							</p>
						{/if}
						<div class="flex flex-col gap-2 sm:flex-row">
							<Input
								type="email"
								bind:value={claimEmail}
								placeholder="you@company.com"
								autocomplete="email"
								required
								class="flex-1"
							/>
							<Button type="submit" class="gap-2" disabled={claimState === "sending"}>
								<Mail class="size-3.5" />
								{claimState === "sending" ? "Sending…" : "Email me a link"}
							</Button>
						</div>
					</form>
					<div class="mt-2">
						<Button href="/dashboard" variant="outline" class="w-full gap-2">
							<LayoutDashboard class="size-3.5" />
							Back to dashboard
						</Button>
					</div>
				{/if}
			{:else}
			<div class="mt-5 flex flex-col gap-2">
				{#if deniedAccess.sameTeam && deniedAccess.ownerEmail}
					<Button
						href={`mailto:${deniedAccess.ownerEmail}?subject=${encodeURIComponent("Doove access request")}&body=${encodeURIComponent("Hi — could you share access to this doove with me? " + (browser ? window.location.href : ""))}`}
						class="gap-2"
					>
						<Mail class="size-3.5" />
						Request access from {deniedAccess.ownerEmail}
					</Button>
				{:else if viewer == null}
					<Button href={`/login?next=${encodeURIComponent(browser ? window.location.pathname + window.location.search : "")}`} class="gap-2">
						<User class="size-3.5" />
						Sign in to check access
					</Button>
				{/if}
				<Button href="/dashboard" variant="outline" class="gap-2">
					<LayoutDashboard class="size-3.5" />
					Back to dashboard
				</Button>
			</div>
			{/if}
		</div>
	</div>
{:else if requiresPassword}
	<!-- Password-protected share. Same chrome as the denial card. -->
	<div class="relative grid min-h-screen place-items-center px-6 py-16 text-foreground">
		<div
			aria-hidden="true"
			class="pointer-events-none absolute inset-0 -z-10"
			style="background: radial-gradient(ellipse 60% 40% at 50% 0%, color-mix(in srgb, var(--color-primary) 6%, transparent), transparent 70%);"
		></div>
		<div
			aria-hidden="true"
			class="bg-grid bg-grid-fade pointer-events-none absolute inset-0 -z-10 opacity-25"
		></div>

		<form
			class="glass-card w-full max-w-md rounded-2xl border border-border-low/40 p-7 shadow-craft-xl"
			in:scale={{ start: 0.96, duration: 320, easing: quintOut, opacity: 0.6 }}
			onsubmit={submitUnlock}
		>
			<div class="flex items-start gap-3">
				<span class="grid size-10 shrink-0 place-items-center rounded-xl bg-foreground/5 text-foreground ring-1 ring-border/40">
					<Lock class="size-5" />
				</span>
				<div class="min-w-0">
					<h1 class="text-lg font-semibold tracking-tight">Password required</h1>
					<p class="mt-1 text-sm text-muted-foreground">
						This doove is password-protected. Enter the password the owner shared with you.
					</p>
				</div>
			</div>

			<label class="mt-5 block">
				<span class="sr-only">Password</span>
				<input
					type="password"
					required
					autocomplete="current-password"
					bind:value={passwordInput}
					class="w-full rounded-lg border border-border-low/70 bg-background/80 px-3.5 py-2.5 text-sm text-foreground outline-none transition-colors placeholder:text-muted-foreground/70 focus:border-primary/60"
					placeholder="Password"
					disabled={unlocking}
				/>
			</label>

			{#if unlockError}
				<p class="mt-2 text-xs text-destructive">{unlockError}</p>
			{/if}

			<div class="mt-4 flex flex-col gap-2">
				<Button type="submit" disabled={unlocking || !passwordInput} class="gap-2">
					{unlocking ? "Unlocking…" : "Unlock"}
					{#if !unlocking}<ArrowRight class="size-3.5" />{/if}
				</Button>
			</div>
		</form>
	</div>
{:else}
	<!-- ── Standard share view ─────────────────────────────────────────
	     Single, viewer-first layout: quiet top bar → player hero → title
	     + meta + CTA → reactions + comments. No "view modes": a stranger
	     should be able to watch with zero learning curve. -->
	<div
		class="relative min-h-screen text-foreground"
		in:fade={{ duration: 360, easing: quintOut }}
	>
		<div
			aria-hidden="true"
			class="pointer-events-none absolute inset-0 -z-10"
			style="background: radial-gradient(ellipse 70% 50% at 50% 0%, color-mix(in srgb, var(--color-primary) 9%, transparent), transparent 72%);"
		></div>
		<div
			aria-hidden="true"
			class="bg-grid bg-grid-fade pointer-events-none absolute inset-0 -z-10 opacity-30"
		></div>

		<!-- Top bar — brand left, light viewer/owner actions right. The mode
		     switcher is gone; the only chrome here is theme, share, account. -->
		<header class="sticky top-0 z-30 border-b border-border-low/30 bg-background/70 backdrop-blur-xl">
			<div class="relative mx-auto flex max-w-4xl items-center gap-3 px-5 py-3 sm:px-6">
				<!-- Left mark. For Pro shares this should swap to the owner's
				     custom logo (branding feature, not wired yet) — the slot is
				     here so that change is a one-line conditional later. -->
				<a href="/" class="group/logo flex shrink-0 items-center gap-2.5" aria-label="Doove — home">
					<span class="grid size-9 place-items-center rounded-xl bg-foreground p-1 text-background shadow-craft-sm transition-transform group-hover/logo:rotate-[-4deg]">
						<Logo size="22" color="transparent" fill="currentColor" />
					</span>
					<span class="text-base font-semibold tracking-tight text-foreground max-sm:hidden">Doove</span>
				</a>

				<!-- Scroll-aware context — absolutely centered so it never
				     shifts the logo/actions, pointer-events-none so it's purely
				     informational. Fades in once the title scrolls away. -->
				{#if showBarTitle && doove}
					<div
						class="pointer-events-none absolute left-1/2 flex max-w-[52%] -translate-x-1/2 items-center gap-2"
						in:fly={{ y: -6, duration: 200, easing: cubicOut }}
						out:fade={{ duration: 140 }}
					>
						<span class="grid size-6 shrink-0 place-items-center rounded-full bg-foreground/10 text-[9px] font-bold text-foreground ring-1 ring-border/40">
							{initials(doove.sharedBy, null)}
						</span>
						<span class="truncate text-sm font-medium text-foreground/90">{doove.title}</span>
					</div>
				{/if}

				<div class="ml-auto flex shrink-0 items-center gap-2">
					<!-- Theme toggle -->
					<Tooltip.Provider delayDuration={300}>
						<Tooltip.Root>
							<Tooltip.Trigger
								onclick={toggleMode}
								aria-label={themeMode.current === "dark" ? "Switch to light mode" : "Switch to dark mode"}
								class="group/theme grid size-9 shrink-0 place-items-center rounded-xl border border-border/40 bg-foreground/5 text-muted-foreground transition-colors hover:bg-foreground/10 hover:text-foreground focus-visible:outline-2 focus-visible:outline-primary"
							>
								<span class="relative grid size-3.5 place-items-center">
									{#if themeMode.current === "dark"}
										<span class="absolute" in:fly={{ y: 4, duration: 180, easing: cubicOut }} out:fade={{ duration: 120 }}>
											<Sun class="size-3.5" />
										</span>
									{:else}
										<span class="absolute" in:fly={{ y: -4, duration: 180, easing: cubicOut }} out:fade={{ duration: 120 }}>
											<Moon class="size-3.5" />
										</span>
									{/if}
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content sideOffset={8}>
								<span class="text-[11px]">{themeMode.current === "dark" ? "Light mode" : "Dark mode"}</span>
							</Tooltip.Content>
						</Tooltip.Root>
					</Tooltip.Provider>

					<!-- Share menu — viewer actions on top; owner controls (who
					     can view, comments, CTA, analytics) gated behind canManage. -->
					<DropdownMenu.Root>
						<DropdownMenu.Trigger
							class="group/share inline-flex h-9 items-center gap-1.5 rounded-xl border border-transparent bg-primary px-3 text-xs font-semibold text-primary-foreground shadow-craft-sm transition-all hover:scale-[1.02] hover:bg-primary/95 active:scale-[0.98] focus-visible:outline-2 focus-visible:outline-primary"
						>
							<Share2 class="size-3.5" />
							<span class="max-sm:hidden">Share</span>
						</DropdownMenu.Trigger>
						<DropdownMenu.Content align="end" sideOffset={6} class="w-64">
							<DropdownMenu.Label class="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">
								Share this doove
							</DropdownMenu.Label>
							<DropdownMenu.Item onclick={copyShareLink} class="gap-2.5">
								<Copy class="size-3.5 text-muted-foreground" />
								Copy link
							</DropdownMenu.Item>
							<DropdownMenu.Item onclick={copyLinkAtCurrentTime} class="gap-2.5">
								<Link2 class="size-3.5 text-muted-foreground" />
								Copy link at
								<span class="ml-auto font-mono text-[10px] tabular-nums text-foreground">{formatTime(currentTime)}</span>
							</DropdownMenu.Item>
							<DropdownMenu.Item onclick={copyEmbedCode} class="gap-2.5">
								<Code class="size-3.5 text-muted-foreground" />
								Copy embed code
							</DropdownMenu.Item>
							{#if canManage}
								<!-- Downloading the original master is an owner/admin
								     action only — viewers stream but can't pull the file. -->
								<DropdownMenu.Separator />
								<DropdownMenu.Item onclick={() => browser && doove && window.open(doove.src, "_blank")} class="gap-2.5">
									<Download class="size-3.5 text-muted-foreground" />
									Download original
								</DropdownMenu.Item>
								<DropdownMenu.Separator />
								<DropdownMenu.Label class="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">
									Who can view
								</DropdownMenu.Label>
								{#if isSelectedScope}
									<!-- Current scope is the specific-people allowlist. It's set
									     up from the share dialog (not editable inline), so we show
									     it as the active state and let the owner switch to a
									     standard scope below. -->
									<div class="flex items-center gap-2.5 rounded-md px-2 py-1.5">
										<UserCheck class="size-3.5 text-primary" />
										<div class="flex-1 min-w-0">
											<div class="text-xs font-medium text-foreground">Specific people</div>
											<div class="text-[10px] text-muted-foreground">Only invited people can view</div>
										</div>
										<Check class="size-3.5 text-primary" />
									</div>
								{/if}
								{#each [
									{ id: "public" as const, label: "Anyone with the link", icon: Globe },
									{ id: "team" as const, label: "Only my team", icon: Users },
									{ id: "private" as const, label: "Only me", icon: Lock },
								] as opt (opt.id)}
									{@const active = activeScope === opt.id}
									<DropdownMenu.Item
										disabled={updatingVisibility}
										onSelect={(e) => {
											e.preventDefault();
											updateVisibility(opt.id);
										}}
										class="gap-2.5"
									>
										<opt.icon class={cn("size-3.5", active ? "text-primary" : "text-muted-foreground")} />
										<div class="flex-1 min-w-0">
											<div class={cn("text-xs", active && "font-medium text-foreground")}>{opt.label}</div>
										</div>
										{#if active}<Check class="size-3.5 text-primary" />{/if}
									</DropdownMenu.Item>
								{/each}

								<DropdownMenu.Separator />
								<DropdownMenu.Label class="text-[10px] uppercase tracking-[0.14em] text-muted-foreground">
									Engagement
								</DropdownMenu.Label>
								<DropdownMenu.Item onclick={openCtaEditor} class="gap-2.5">
									<Megaphone class="size-3.5 text-muted-foreground" />
									{cta ? "Edit call-to-action" : "Add a call-to-action"}
								</DropdownMenu.Item>
								<DropdownMenu.Item
									onSelect={(e) => {
										e.preventDefault();
										toggleCommentsEnabled();
									}}
									class="gap-2.5"
								>
									<MessageSquare class="size-3.5 text-muted-foreground" />
									<div class="flex-1 min-w-0"><div class="text-xs">Comments</div></div>
									<span class={cn("font-mono text-[10px] uppercase", commentsEnabled ? "text-primary" : "text-muted-foreground")}>
										{commentsEnabled ? "On" : "Off"}
									</span>
								</DropdownMenu.Item>
								<DropdownMenu.Item onclick={() => goto("/dashboard/analytics")} class="gap-2.5">
									<Eye class="size-3.5 text-muted-foreground" />
									View analytics
								</DropdownMenu.Item>
							{/if}
						</DropdownMenu.Content>
					</DropdownMenu.Root>

					{#if viewer}
						<DropdownMenu.Root>
							<DropdownMenu.Trigger
								aria-label="Account menu — {viewer.name || viewer.email}"
								class="grid size-9 shrink-0 place-items-center overflow-hidden rounded-full bg-foreground text-[11px] font-bold text-background ring-1 ring-border/40 transition-transform hover:scale-105 focus-visible:outline-2 focus-visible:outline-primary"
							>
								{#if viewer.image}
									<img src={viewer.image} alt="" referrerpolicy="no-referrer" class="size-full object-cover" />
								{:else}
									{initials(viewer.name, viewer.email)}
								{/if}
							</DropdownMenu.Trigger>
							<DropdownMenu.Content align="end" sideOffset={8} class="w-64">
								<div class="flex items-center gap-2.5 px-2 py-2.5">
									<span class="grid size-9 shrink-0 place-items-center overflow-hidden rounded-full bg-foreground text-[12px] font-bold text-background ring-1 ring-border/40">
										{#if viewer.image}
											<img src={viewer.image} alt="" referrerpolicy="no-referrer" class="size-full object-cover" />
										{:else}
											{initials(viewer.name, viewer.email)}
										{/if}
									</span>
									<div class="min-w-0 flex-1">
										<div class="truncate text-sm font-semibold text-foreground">{viewer.name || "Doove user"}</div>
										<div class="truncate font-mono text-[10px] text-muted-foreground">{viewer.email}</div>
									</div>
								</div>
								<DropdownMenu.Separator />
								<DropdownMenu.Item onclick={() => goto("/dashboard")} class="gap-2.5">
									<LayoutDashboard class="size-3.5 text-muted-foreground" />
									Dashboard
								</DropdownMenu.Item>
								<DropdownMenu.Item onclick={() => goto("/dashboard/dooves")} class="gap-2.5">
									<Film class="size-3.5 text-muted-foreground" />
									My dooves
								</DropdownMenu.Item>
								<DropdownMenu.Item onclick={() => goto("/dashboard/settings/profile")} class="gap-2.5">
									<Settings class="size-3.5 text-muted-foreground" />
									Account settings
								</DropdownMenu.Item>
								<DropdownMenu.Separator />
								<DropdownMenu.Item onclick={signOut} class="gap-2.5 text-destructive focus:bg-destructive/10 focus:text-destructive">
									<LogOut class="size-3.5" />
									Sign out
								</DropdownMenu.Item>
							</DropdownMenu.Content>
						</DropdownMenu.Root>
					{:else if currentScope !== "public"}
						<!-- Strangers on a public link have nothing to gain from
						     signing in, so the nudge only shows on team/private
						     links where an account could unlock access. -->
						<Button href="/login" size="sm" variant="outline" class="gap-1.5">
							<User class="size-3.5" />
							<span class="max-sm:hidden">Sign in</span>
						</Button>
					{/if}
				</div>
			</div>
		</header>

		<main class="mx-auto max-w-4xl px-5 pb-20 pt-6 sm:px-6">
			<!-- Player hero. End-card overlays the player when the video ends
			     AND the owner set a CTA — the highest-intent moment to ask
			     for the next step. -->
			<section class="relative">
				<div class="glass-card relative overflow-hidden rounded-2xl shadow-craft-xl">
					{#if doove?.src}
						<DoovePlayer
							bind:api
							src={doove.src}
							poster={doove.poster}
							title={doove.title}
							aspectRatio={playerAspect}
							onengagement={onEngagement}
						/>
					{:else}
						<div class="grid aspect-video place-items-center bg-foreground/5 text-sm text-muted-foreground">
							Playback is unavailable for this doove.
						</div>
					{/if}

					{#if showEndCard && cta}
						<!-- z-50 lifts the end-card above the player's controls
						     (media-chrome tops out at z-index 6); without it the
						     center play button sits on top and eats the clicks
						     meant for the CTA / Replay. -->
						<div
							class="absolute inset-0 z-50 grid place-items-center bg-black/70 backdrop-blur-sm"
							in:fade={{ duration: 220, easing: cubicOut }}
						>
							<div class="flex flex-col items-center gap-4 px-6 text-center" in:scale={{ start: 0.95, duration: 280, easing: quintOut, opacity: 0.4 }}>
								<p class="text-sm font-medium text-white/70">Thanks for watching</p>
								<Button href={cta.url} target="_blank" rel="noopener" size="lg" class="gap-2">
									{cta.label}
									<ExternalLink class="size-4" />
								</Button>
								<button
									type="button"
									onclick={replay}
									class="inline-flex items-center gap-1.5 text-xs font-medium text-white/60 transition-colors hover:text-white"
								>
									<RotateCcw class="size-3.5" />
									Replay
								</button>
							</div>
						</div>
					{/if}
				</div>
			</section>

			<!-- Title + meta. Sits below the video (video-first), with view
			     count as quiet social proof. -->
			<div class="mt-5">
				<h1
					bind:this={titleAnchorEl}
					class="text-balance text-2xl font-semibold leading-tight tracking-tight sm:text-3xl"
				>
					{doove?.title}
				</h1>
				<div class="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted-foreground">
					<span>Shared by <span class="font-medium text-foreground">{doove?.sharedBy}</span></span>
					<span aria-hidden="true">·</span>
					<span>{doove ? new Date(doove.sharedAt).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : ""}</span>
					{#if doove?.durationSec}
						<span aria-hidden="true">·</span>
						<span class="font-mono tabular-nums">{formatTime(doove.durationSec)}</span>
					{/if}
					{#if viewsCount > 0}
						<span aria-hidden="true">·</span>
						<span class="inline-flex items-center gap-1">
							<Eye class="size-3" />
							{viewsCount.toLocaleString()} {viewsCount === 1 ? "view" : "views"}
						</span>
					{/if}
				</div>
				{#if doove?.description}
					<p class="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">{doove.description}</p>
				{/if}
			</div>

			<!-- Persistent CTA — the founder's "next step", always visible (the
			     end-card only catches viewers who finish). -->
			{#if cta}
				<div class="mt-4">
					<Button href={cta.url} target="_blank" rel="noopener" class="gap-2">
						{cta.label}
						<ExternalLink class="size-3.5" />
					</Button>
				</div>
			{:else if canManage}
				<button
					type="button"
					onclick={openCtaEditor}
					class="mt-4 inline-flex items-center gap-2 rounded-xl border border-dashed border-border-low/70 px-3.5 py-2 text-xs font-medium text-muted-foreground transition-colors hover:border-primary/50 hover:text-foreground"
				>
					<Megaphone class="size-3.5" />
					Add a call-to-action
				</button>
			{/if}

			<!-- Reactions — lightweight sentiment, always available. -->
			<div class="mt-6 flex flex-wrap items-center gap-2">
				{#each REACTION_EMOJI as emoji (emoji)}
					{@const count = countFor(emoji)}
					{@const mine = myReactions.has(emoji)}
					<button
						type="button"
						onclick={() => react(emoji)}
						aria-pressed={mine}
						class={cn(
							"inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-sm transition-all",
							mine
								? "border-primary/40 bg-primary/12 text-foreground"
								: "border-border-low/60 bg-foreground/3 text-muted-foreground hover:border-border hover:bg-foreground/6",
						)}
					>
						<span class="leading-none">{emoji}</span>
						{#if count > 0}
							<span class="font-mono text-[11px] tabular-nums">{count}</span>
						{/if}
					</button>
				{/each}
				{#if totalReactions > 0}
					<span class="ml-1 text-xs text-muted-foreground">{totalReactions} {totalReactions === 1 ? "reaction" : "reactions"}</span>
				{/if}
			</div>

			<!-- Comments — collapsible disclosure, only when the owner allows
			     them. Name-only: viewers comment without an account. -->
			{#if commentsEnabled}
				<section class="mt-6">
					<button
						type="button"
						onclick={() => (commentsOpen = !commentsOpen)}
						class="flex w-full items-center gap-2 rounded-xl px-1 py-1.5 text-left transition-colors hover:text-foreground"
						aria-expanded={commentsOpen}
					>
						<MessageSquare class="size-4 text-muted-foreground" />
						<span class="text-sm font-semibold">Comments</span>
						<span class="rounded-md bg-foreground/8 px-1.5 py-0.5 font-mono text-[10px] tabular-nums text-muted-foreground">
							{comments.length}
						</span>
						<ChevronDown class={cn("ml-auto size-4 text-muted-foreground transition-transform", commentsOpen && "rotate-180")} />
					</button>

					{#if commentsOpen}
						<div class="mt-2" transition:slide={{ duration: 220, easing: cubicOut }}>
							<!-- Composer -->
							<div class="glass-card rounded-2xl border border-border-low/40 p-3 shadow-craft-sm">
								<div class="flex flex-col gap-2 sm:flex-row sm:items-center">
									<input
										bind:value={viewerName}
										type="text"
										placeholder="Your name"
										maxlength="60"
										class="w-full rounded-lg border border-border-low/70 bg-background/80 px-3 py-2 text-xs text-foreground outline-none transition-colors placeholder:text-muted-foreground/70 focus:border-primary/60 sm:w-36 sm:shrink-0"
									/>
									<div class="flex flex-1 items-center gap-2">
										<input
											bind:this={inputEl}
											bind:value={draftText}
											type="text"
											placeholder="Comment at {formatTime(currentTime)}…"
											onkeydown={(e) => {
												if (e.key === "Enter" && !e.shiftKey) {
													e.preventDefault();
													submitComment();
												}
											}}
											class="min-w-0 flex-1 rounded-lg border border-border-low/70 bg-background/80 px-3 py-2 text-xs text-foreground outline-none transition-colors placeholder:text-muted-foreground/70 focus:border-primary/60"
										/>
										<Tooltip.Provider delayDuration={250}>
											<Tooltip.Root>
												<Tooltip.Trigger
													onclick={insertCurrentTimestamp}
													aria-label="Insert current timestamp"
													class="grid size-9 shrink-0 place-items-center rounded-lg border border-border-low/70 bg-background/80 text-muted-foreground transition-colors hover:bg-foreground/5 hover:text-foreground"
												>
													<Clock class="size-3.5" />
												</Tooltip.Trigger>
												<Tooltip.Content sideOffset={8}>
													<span class="text-[11px]">Insert <span class="font-mono">[{formatTime(currentTime)}]</span></span>
												</Tooltip.Content>
											</Tooltip.Root>
										</Tooltip.Provider>
										<Button size="sm" class="shrink-0 gap-1.5" disabled={!draftText.trim() || !viewerName.trim()} onclick={submitComment}>
											Post
											<ArrowRight class="size-3.5" />
										</Button>
									</div>
								</div>
								<p class="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 px-1 text-[10px] text-muted-foreground">
									<span class="inline-flex items-center gap-1"><Clock class="size-2.5" /><span class="font-mono">[m:ss]</span> jumps to a time</span>
									<span aria-hidden="true">·</span>
									<span class="inline-flex items-center gap-1"><AtSign class="size-2.5" /><span class="font-mono">@name</span> mentions someone</span>
								</p>
							</div>

							<!-- Thread -->
							{#if comments.length === 0}
								<p class="mt-4 px-1 text-sm text-muted-foreground">No comments yet — be the first.</p>
							{:else}
								<ul class="mt-2">
									{#each comments as c (c.id)}
										{@const within = Math.abs(c.atSeconds - smoothedTime.current) < 5}
										<li
											class={cn(
												"group/comment flex items-start gap-3 rounded-xl px-2 py-3 transition-colors",
												within ? "bg-primary/8" : "hover:bg-foreground/4",
											)}
										>
											<button
												type="button"
												onclick={() => jumpTo(c.atSeconds)}
												aria-label="Jump to {c.authorName}'s comment at {formatTime(c.atSeconds)}"
												class="grid size-8 shrink-0 place-items-center rounded-full text-[11px] font-bold text-white transition-transform hover:scale-105"
												style="background: hsl({commentHue(c.authorName)} 60% 45%);"
											>
												{c.authorName[0]?.toUpperCase()}
											</button>
											<div class="min-w-0 flex-1">
												<div class="flex items-center gap-2">
													<span class="text-sm font-semibold">{c.authorName}</span>
													<button
														type="button"
														onclick={() => jumpTo(c.atSeconds)}
														class={cn("font-mono text-[10px] tabular-nums transition-colors hover:text-primary", within ? "text-primary" : "text-muted-foreground")}
													>
														{formatTime(c.atSeconds)}
													</button>
													{#if c.mine || canManage}
														<button
															type="button"
															onclick={() => removeComment(c.id)}
															aria-label="Delete comment"
															class="ml-auto grid size-6 shrink-0 place-items-center rounded-md text-muted-foreground opacity-0 transition-all hover:bg-destructive/10 hover:text-destructive focus-visible:opacity-100 group-hover/comment:opacity-100"
														>
															<Trash2 class="size-3" />
														</button>
													{/if}
												</div>
												<p class="mt-0.5 text-[13px] leading-relaxed text-foreground/85">
													{#each parseCommentText(c.body) as seg, i (i)}
														{#if seg.kind === "text"}<!--
														-->{seg.text}<!--
													-->{:else if seg.kind === "timestamp"}<!--
														--><button
															type="button"
															onclick={() => jumpTo(seg.seconds)}
															class="mx-px inline-flex -translate-y-px items-center px-1 align-middle text-[11px] font-medium text-primary transition-colors hover:underline"
														>{formatTime(seg.seconds)}</button><!--
													-->{:else if seg.kind === "mention"}<!--
														--><span class="mx-px rounded-md bg-foreground/10 px-1 font-medium text-foreground">@{seg.name}</span><!--
													-->{/if}
													{/each}
												</p>
											</div>
										</li>
									{/each}
								</ul>
							{/if}
						</div>
					{/if}
				</section>
			{/if}

			<!-- Free-tier growth loop: every shared link quietly markets
			     Doove. Pro removes the watermark, so this hides for them. -->
			{#if watermark}
				<footer class="mt-12 flex justify-center">
					<a
						href="/"
						class="group/made inline-flex items-center gap-2 rounded-full border border-border-low/40 bg-foreground/3 px-3 py-1.5 text-[11px] text-muted-foreground transition-colors hover:border-border hover:text-foreground"
					>
						<span class="grid size-4 place-items-center rounded bg-foreground p-0.5 text-background">
							<Logo size="12" color="transparent" fill="currentColor" />
						</span>
						Made with <span class="font-semibold text-foreground">Doove</span>
					</a>
				</footer>
			{/if}
		</main>
	</div>

	<!-- Owner CTA editor — opened from the Share menu, kept off the viewer
	     surface entirely. -->
	{#if canManage}
		<Dialog.Root bind:open={ctaDialogOpen}>
			<Dialog.Content>
				<Dialog.Header>
					<Dialog.Title class="flex items-center gap-2">
						<span class="glass-chip grid size-7 place-items-center rounded-lg text-primary">
							<Megaphone class="size-3.5" />
						</span>
						Call-to-action
					</Dialog.Title>
					<Dialog.Description>
						The next step you want viewers to take — shown as a button below the video and when it ends.
					</Dialog.Description>
				</Dialog.Header>
				<form class="space-y-3" onsubmit={saveCta}>
					<Label class="block">
						<span class="mb-1 block text-xs font-semibold text-foreground/85">Button text</span>
						<Input bind:value={ctaLabelDraft} placeholder="Book a 15-min call" maxlength={60} class="h-10" />
					</Label>
					<Label class="block">
						<span class="mb-1 block text-xs font-semibold text-foreground/85">Link</span>
						<Input bind:value={ctaUrlDraft} placeholder="https://cal.com/you/intro" type="url" class="h-10" />
					</Label>
					<Dialog.Footer class="gap-2">
						{#if cta}
							<Button
								type="button"
								variant="ghost"
								class="mr-auto text-destructive hover:bg-destructive/10 hover:text-destructive"
								onclick={() => {
									ctaLabelDraft = "";
									ctaUrlDraft = "";
								}}
							>
								Clear
							</Button>
						{/if}
						<Button type="button" variant="ghost" onclick={() => (ctaDialogOpen = false)}>Cancel</Button>
						<Button type="submit" disabled={savingCta} class="gap-2">
							{savingCta ? "Saving…" : "Save"}
							{#if !savingCta}<Check class="size-4" />{/if}
						</Button>
					</Dialog.Footer>
				</form>
			</Dialog.Content>
		</Dialog.Root>
	{/if}
{/if}
